### ISSUE TITLE
"subject" not in "promt"

### ISSUE THREAD

**Issue by XZhang00** [Vicky-Wil/ReMaKE#1]
Hi! Thanks for your open-sourced data and code.

When I ran the rome experiment, I found that in many languages the "subject" is not in "src", which will cause an error in the rome algorithm. How to solve this problem?

Looking forward to your reply.

<img width="1141" alt="image" src="https://github.com/Vicky-Wil/ReMaKE/assets/44473150/b64927ab-21da-449f-b6e6-787adb1f3791">

<img width="1035" alt="image" src="https://github.com/Vicky-Wil/ReMaKE/assets/44473150/2088e31b-c6fb-44b5-aa94-896b2187072f">

**Comment by weixuan-wang123** [comment]
Thank you for your attention. As the test sets are translated by the Google Translation, there sometimes a mismatch occurs between the translation of subject and the translation of sentence. You could use fuzzy matching to locate the subject, or skip mismatches directly.
